name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.in
      - name: Run tests (pytest)
        run: |
          set -o pipefail
          cd backend
          pytest -q 2>&1 | tee ../test-output.txt
      - name: Upload pytest output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.txt
